notifications:
  email:
    on_success: never
    on_failure: always

language: node_js
node_js:
  - 8

install:
  - npm install
  - npm install -g bower
  - bower install
  - npm install -g codecov

cache:
  directories:
    - "node_modules"

script:
  - gulp test
  - codecov

after_success:
  - gulp build

deploy:
  local-dir: build/www
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  fqdn: jsboilerplate-webangularjs.aikaka.net
  on:
    branch: master
