notifications:
  email:
    on_success: never
    on_failure: always

sudo: required

services:
  - docker

language: node_js
node_js:
  - 8

install:
  - npm install
  - npm install -g bower
  - bower install
  - npm install -g codecov

cache:
  directories:
    - "node_modules"

script:
  - gulp test
  - codecov

after_success:
  - gulp build
  - bash Dockerbuild.sh

deploy:
  provider: pages
  local-dir: build/www
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  fqdn: jsboilerplate-angularjs.aikaka.net
  on:
    branch: master

after_deploy:
    - bash Dockerpush.sh
